version: "3.8"
services:
  # mysql:
  #   image: mysql
  #   container_name: my-mysql
  #   volumes: 
  #     - type: bind
  #       source: ./mysqldir
  #       target: /var/lib/mysql
  #   ports:
  #     - '3307:3306'
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=Nlsc!1234567
  apollo: 
    env_file: .env
    build: .
    ports: 
      - "4123:4000"
    container_name: my-apollo
    links:
      - mysql
    volumes:
      - type: bind
        source: ./public
        target: /apollotest/public

    # depends_on: 
    #   - db
      #資料庫實體位置
      #C:\ProgramData\MySQL\MySQL Server 8.0\Data